#pragma config(Sensor, port2,  Compass,        sensorVexIQ_Gyro)
#pragma config(Sensor, port3,  RGB,            sensorVexIQ_LED)
#pragma config(Motor,  motor1,          armMotor1,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          armMotor2,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor8,          Rspike,        tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor9,          rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor11,         Lspike,        tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//int A, B;
//int left, right;
//A = getjoystickvalue(ChA);
//B = getjoystickvalue(ChB);
//left = A + B;
//right = A - B;
//motor[leftmotor] = left*0.9;
//motor[rightmotor] = right*0.9;

//arcade o
int ArcadeOMapTurbo[101] = {
	0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,
	10,10,10,10,10,10,10,10,10,10,
	10,10,10,10,10,10,10,10,10,10,
	20,20,20,20,20,20,20,20,20,20,
	30,30,30,30,30,30,30,30,30,30,
	40,40,40,40,40,40,40,40,40,40,
	50,50,50,50,50,50,50,50,50,50,
	60,62,64,66,68,70,72,74,76,78,
	84,88,92,96,100,100,100,100,100,100,100};

int ArcadeOMapNurbo[101] = {0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,
	10,10,10,10,10,10,10,10,10,10,
	10,10,10,10,10,10,10,10,10,10,
	20,20,20,20,20,20,20,20,20,20,
	20,20,20,20,20,20,20,20,20,20,
	20,20,20,20,20,20,20,20,20,20,
	30,30,30,30,30,30,30,30,30,30,
	30,30,30,30,30,30,30,30,30,30,
	40,40,40,40,40,40,40,40,40,40,40};

enum arm_def {Nothing, BTOM = 0, YELO = 790, TOP = 934, BARM = -140, lvl2 = 380, lvl3 = 590};
enum spike_def {Nothing, Spike1 = -280, Spike2 = -130, Spike3 = 0};

arm_def arms = Nothing;
spike_def spikes = Nothing;

task main(){

	//this has to change srry
	int Lspiker = 3;
	int Rspiker = 3;
	bool yesL = true, yesL2 = true, yesR = true, yesR2 = true;

	//cntrl def.
	string TURBO = "sad";
	int x = 0;
	int y = 0;
	int left = 0;
	int right = 0;

	while(true){
		//arcade r
		if(abs(vexRT[ChA]) > 15){
			x = vexRT[ChA];
		}else{
			x = 0;
		}

		x = sgn(x) * ArcadeOMapTurbo[abs(x)];

		if(abs(vexRT[ChB]) > 15){
			y = vexRT[ChB];
		}else{
			y = 0;
		}

		y = sgn(y) * ArcadeOMapTurbo[abs(y)] / 2;

		left = x + y;
		right = x - y;

		motor[leftMotor] = left * 0.9;
		motor[rightMotor] = right * 0.9;


		if(vexRT[ChD] >= 50){
			arms = lvl3;
			setMotorTarget(armMotor1, arms, 127);
			setMotorTarget(armMotor2, arms, 127);
		}
		if(vexRT[ChD] <= -50){
			arms = lvl2;
			setMotorTarget(armMotor1, arms, 127);
			setMotorTarget(armMotor2, arms, 127);
		}

		//bottom
		if(vexRT[BtnEDown] == 1){
			arms = BTOM;
			setMotorTarget(armMotor1, arms, 127);
			setMotorTarget(armMotor2, arms, 127);
		}//yellow
		if(vexRT[BtnEUp] == 1){
			arms = YELO;
			setMotorTarget(armMotor1, arms, 127);
			setMotorTarget(armMotor2, arms, 127);
		}//top
		if(vexRT[BtnFUp] == 1){
			arms = TOP;
			setMotorTarget(armMotor1, arms, 127);
			setMotorTarget(armMotor2, arms, 127);
		}

		//back
		if(vexRT[BtnFDown] == 1){
			arms = BARM;
			moveMotorTarget(armMotor1, arms, 127);
			moveMotorTarget(armMotor2, arms, 127);
			setMotorSpeed(leftMotor, -30);
			setMotorSpeed(rightMotor, -30);
			wait1Msec(600);
		}

		//left spike down aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
		if(vexRT[BtnLDown] == 1){
			if(yesL == true){
				if(Lspiker == 1){
					spikes = Spike2;
					setMotorTarget(Lspike, abs(spikes), 100);
					Lspiker = 2;
				}
				else if(Lspiker == 2){
					spikes = Spike3;
					setMotorTarget(Lspike, spikes, 100);
					Lspiker = 3;
				}
				else if(Lspiker == 3){
					spikes = Spike2;
					setMotorTarget(Lspike, abs(spikes), 100);
					Lspiker = 2;
				}
				yesL = false;
			}
		}else{
			yesL = true;
		}

		//left spike up aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
		if(vexRT[BtnLUp] == 1){
			if(yesL2 == true){
				spikes = Spike1;
				if(Lspiker == 1){
					setMotorTarget(Lspike, abs(spikes), 100);
					Lspiker = 1;
				}
				if(Lspiker == 2){
					spikes = Spike1;
					setMotorTarget(Lspike, abs(spikes), 100);
					Rspiker = 1;
				}
				if(Lspiker == 3){
					spikes = Spike1;
					setMotorTarget(Lspike, abs(spikes), 100);
					Rspiker = 1;
				}
				yesL2 = false;
			}
		}else{
				yesL2 = true;
		}

		//right spike down aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
		if(vexRT[BtnRDown] == 1){
			if(yesR == true){
				if(Rspiker == 1){
					spikes = Spike2;
					setMotorTarget(Rspike, spikes, 100);
					Rspiker = 2;
				}
				else if(Rspiker == 2){
					spikes = Spike3;
					setMotorTarget(Rspike, spikes, 100);
					Rspiker = 3;
				}
				else if(Rspiker == 3){
					spikes = Spike2;
					setMotorTarget(Rspike, spikes, 100);
					Rspiker = 2;
				}
				yesR = false;
			}
		}else{
			yesR = true;
		}

		//right spike up aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
		if(vexRT[BtnRUp] == 1){
			if(yesR2 == true){
				spikes = Spike1;
				if(Rspiker == 1){
					setMotorTarget(Rspike, spikes, 100);
					Rspiker = 1;
				}
				if(Rspiker == 2){
					setMotorTarget(Rspike, spikes, 100);
					Rspiker = 1;
				}
				if(Rspiker == 3){
					setMotorTarget(Rspike, spikes, 100);
					Rspiker = 1;
				}
				yesR2 = false;
			}
		}else{
			yesR2 = true;
		}

		//resetting stuffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
		arms = Nothing;
		spikes = Nothing;

	}

}
//russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers russian hackers*
//russian hackers *heart*
