#pragma config(Motor,  motor1,          armMotor2,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          armMotor1,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor8,          rightCatchMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor9,          rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor11,         leftCatchMotor, tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "functions/PID.h"
#include "subsystems/Drive.h"

driveInit(10, 9, true);

task main()
{



}
