#pragma config(Motor,  motor1,          leftArm,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor2,          RightArm,      tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../functions/PID.h"

typedef struct{
	int currentLocation, targetLocation;
	PID_constants armConstants;
	PID_values armValues;
}ARM_VALUES;
