#pragma config(Motor,  motor1,          leftArm,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor2,          RightArm,      tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

typedef struct{
	int currentLocation, targetLocation;

}ARM_VALUES;
